#!/usr/bin/env node
// Builds the GitHub Pages summary index from the blog's RSS feed.
//
//   node tools/build-pages.mjs [--out site] [--feed <url-or-path>]
//
// The page is generated at build time rather than fetched in the browser: the
// blog's nginx does not send CORS headers, so a client-side fetch of feed.xml
// from ralyodio.github.io would be blocked. Generating means no JS at all.
//
// Every entry links to the post on the blog itself — this page is an index,
// not a copy. Nothing here is meant to be read instead of the original.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const DEFAULT_FEED = 'https://dev.profullstack.com/~anthony/blog/feed.xml';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** @param {string[]} argv */
function parseArgs(argv) {
	const flags = {};
	for (let i = 0; i < argv.length; i += 1) {
		if (!argv[i].startsWith('--')) continue;
		const key = argv[i].slice(2);
		const next = argv[i + 1];
		flags[key] = next && !next.startsWith('--') ? (i += 1, next) : true;
	}
	return flags;
}

const esc = (s) =>
	String(s)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');

// Feed text arrives XML-escaped and may carry numeric entities.
const unesc = (s) =>
	String(s)
		.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
		.replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
		.replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
		.replace(/&lt;/g, '<')
		.replace(/&gt;/g, '>')
		.replace(/&quot;/g, '"')
		.replace(/&apos;/g, "'")
		.replace(/&amp;/g, '&')
		.trim();

/**
 * Pull the first <tag>…</tag> out of a chunk of XML.
 *
 * Deliberately regex rather than a parser: the feed is generated by
 * build-feed.mjs in this same repo, so its shape is known and fixed, and a
 * dependency-free build is one less thing to keep patched.
 *
 * @param {string} xml
 * @param {string} tag
 * @returns {string}
 */
function tagText(xml, tag) {
	const m = xml.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, 'i'));
	return m ? unesc(m[1]) : '';
}

/** @param {string} xml */
export function parseFeed(xml) {
	const channel = xml.slice(xml.search(/<channel[\s>]/i));
	const head = channel.slice(0, channel.search(/<item[\s>]/i) >>> 0);

	const items = [...xml.matchAll(/<item[\s>][\s\S]*?<\/item>/gi)].map((m) => {
		const block = m[0];
		const pubDate = tagText(block, 'pubDate');
		const when = new Date(pubDate);
		return {
			title: tagText(block, 'title'),
			link: tagText(block, 'link') || tagText(block, 'guid'),
			description: tagText(block, 'description'),
			author: tagText(block, 'dc:creator'),
			pubDate,
			iso: Number.isNaN(when.getTime()) ? '' : when.toISOString(),
			day: Number.isNaN(when.getTime()) ? '' : when.toISOString().slice(0, 10),
			sortKey: Number.isNaN(when.getTime()) ? 0 : when.getTime(),
		};
	});

	items.sort((a, b) => b.sortKey - a.sortKey);

	return {
		title: tagText(head, 'title') || "Chovy's Blog",
		description: tagText(head, 'description'),
		link: tagText(head, 'link') || 'https://dev.profullstack.com/~anthony/blog/',
		items,
	};
}

/**
 * @param {ReturnType<typeof parseFeed>} feed
 * @param {{ feedUrl: string, builtAt: string }} meta
 */
export function renderPage(feed, meta) {
	const cards = feed.items
		.map(
			(p) => `		<li class="post">
			<h2><a href="${esc(p.link)}">${esc(p.title)}</a></h2>
			<p class="meta"><time datetime="${esc(p.iso)}">${esc(p.day)}</time>${
				p.author ? ` &middot; ${esc(p.author)}` : ''
			}</p>
			<p class="summary">${esc(p.description)}</p>
			<p class="more"><a href="${esc(p.link)}">Read it on the blog &rarr;</a></p>
		</li>`,
		)
		.join('\n');

	const empty = `		<li class="post"><p class="summary">The feed came back with no posts. That is a
			bug in this build, not an empty blog &mdash; go straight to
			<a href="${esc(feed.link)}">the blog</a>.</p></li>`;

	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(feed.title)} &mdash; post summaries</title>
<meta name="description" content="Summaries of the ${feed.items.length} most recent posts from ${esc(feed.title)}. Each one links to the full post on the blog.">
<link rel="canonical" href="${esc(feed.link)}">
<link rel="alternate" type="application/rss+xml" title="${esc(feed.title)}" href="${esc(meta.feedUrl)}">
<style>
:root {
	color-scheme: light dark;
	--bg: #fbfbf9;
	--fg: #1b1b1a;
	--muted: #5d5d57;
	--rule: #e2e2dc;
	--card: #ffffff;
	--accent: #7a3b12;
}
@media (prefers-color-scheme: dark) {
	:root {
		--bg: #14140f;
		--fg: #e8e8e0;
		--muted: #9d9d92;
		--rule: #2b2b24;
		--card: #1c1c16;
		--accent: #e0a06a;
	}
}
* { box-sizing: border-box; }
body {
	margin: 0;
	padding: 3rem 1.25rem 4rem;
	background: var(--bg);
	color: var(--fg);
	font: 16px/1.65 ui-serif, Georgia, "Times New Roman", serif;
}
main { max-width: 46rem; margin: 0 auto; }
a { color: var(--accent); }
header { border-bottom: 1px solid var(--rule); padding-bottom: 1.5rem; margin-bottom: 2rem; }
h1 { font-size: 1.9rem; line-height: 1.2; margin: 0 0 .5rem; }
h1 a { color: inherit; text-decoration: none; }
h1 a:hover { text-decoration: underline; }
.tagline { color: var(--muted); margin: 0 0 1rem; }
.note {
	font-size: .9rem;
	color: var(--muted);
	margin: 0;
	font-family: ui-sans-serif, system-ui, sans-serif;
}
ul.posts { list-style: none; margin: 0; padding: 0; }
li.post {
	background: var(--card);
	border: 1px solid var(--rule);
	border-radius: .6rem;
	padding: 1.25rem 1.4rem;
	margin-bottom: 1rem;
}
li.post h2 { font-size: 1.25rem; line-height: 1.3; margin: 0 0 .3rem; }
li.post h2 a { text-decoration: none; }
li.post h2 a:hover { text-decoration: underline; }
.meta {
	font-family: ui-sans-serif, system-ui, sans-serif;
	font-size: .8rem;
	letter-spacing: .02em;
	text-transform: uppercase;
	color: var(--muted);
	margin: 0 0 .7rem;
}
.summary { margin: 0 0 .8rem; }
.more { margin: 0; font-family: ui-sans-serif, system-ui, sans-serif; font-size: .9rem; }
.more a { text-decoration: none; font-weight: 600; }
.more a:hover { text-decoration: underline; }
footer {
	border-top: 1px solid var(--rule);
	margin-top: 2.5rem;
	padding-top: 1.25rem;
	font-family: ui-sans-serif, system-ui, sans-serif;
	font-size: .85rem;
	color: var(--muted);
}
footer a { text-decoration: none; }
footer a:hover { text-decoration: underline; }
</style>
</head>
<body>

<main>

<header>
	<h1><a href="${esc(feed.link)}">${esc(feed.title)}</a></h1>
	<p class="tagline">${esc(feed.description)}</p>
	<p class="note">Summaries only, built from the
		<a href="${esc(meta.feedUrl)}">RSS feed</a>. Every post below opens on the blog itself.</p>
</header>

<ul class="posts">
${cards || empty}
</ul>

<footer>
	<p><a href="${esc(feed.link)}">Read the blog</a> &middot;
		<a href="${esc(meta.feedUrl)}">Subscribe by RSS</a> &middot;
		<a href="https://kagi.com/smallweb/?search=profullstack">Kagi Small Web</a></p>
	<p>The feed carries the 10 most recent posts, so that is what this page shows. The
		full archive lives on <a href="${esc(feed.link)}">the blog</a>.</p>
	<p>Generated from the feed on ${esc(meta.builtAt)}.</p>
</footer>

</main>

</body>
</html>
`;
}

/** @param {string} source url or local path */
async function loadFeed(source) {
	if (/^https?:\/\//.test(source)) {
		const res = await fetch(source, { headers: { 'user-agent': 'blog-pages-builder' } });
		if (!res.ok) throw new Error(`${source} responded ${res.status}`);
		return res.text();
	}
	return readFile(source, 'utf8');
}

async function main() {
	const flags = parseArgs(process.argv.slice(2));
	const feedUrl = typeof flags.feed === 'string' ? flags.feed : process.env.FEED_URL || DEFAULT_FEED;
	const outDir = resolve(root, typeof flags.out === 'string' ? flags.out : 'site');

	let xml;
	try {
		xml = await loadFeed(feedUrl);
	} catch (err) {
		// The blog is on a single box. If it is down at build time, fall back to the
		// feed committed in this repo rather than publishing an empty page.
		console.warn(`could not read ${feedUrl}: ${err.message}`);
		console.warn('falling back to the committed feed.xml');
		xml = await readFile(join(root, 'feed.xml'), 'utf8');
	}

	const feed = parseFeed(xml);
	if (feed.items.length === 0) throw new Error('feed parsed to zero items — refusing to publish');

	const canonicalFeedUrl = /^https?:\/\//.test(feedUrl) ? feedUrl : DEFAULT_FEED;
	const html = renderPage(feed, {
		feedUrl: canonicalFeedUrl,
		builtAt: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
	});

	await mkdir(outDir, { recursive: true });
	await writeFile(join(outDir, 'index.html'), html);
	await writeFile(join(outDir, '.nojekyll'), '');

	console.log(`wrote ${join(outDir, 'index.html')} — ${feed.items.length} post(s)`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
	main().catch((err) => {
		console.error(err.message);
		process.exit(1);
	});
}
